from app.extensions import db
import datetime


class Group(db.Model):
    """
    Database table to store groups (dyads).

    Warm-up is decided server-side at /action time from the cohort size and
    the dyad's cp_message decision count (API-Spec §3.2); it is not a
    per-dyad host flag and is not stored here.
    """

    __tablename__ = "groups"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), unique=True, nullable=False)
    group_info = db.Column(db.JSON, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        group_id: str,
        group_info: dict,
        created_at: datetime.datetime | None = None,
    ):
        """
        Initialize the Group object.
        """
        if created_at is None:
            created_at = datetime.datetime.now()
        self.group_id = group_id
        self.group_info = group_info
        self.created_at = created_at

    def __repr__(self):
        """
        Return a string representation of the Group object.
        """
        return f"<Group group_id={self.group_id} created_at={self.created_at}>"


class DataUpload(db.Model):
    """
    Append-only log of every /upload_data call (API-Spec §6.3).

    Each row is a full flat snapshot of every variable in the field
    dictionary (`data.X` always present, possibly the literal "miss").
    The "current value of field X for dyad Y" is `data.X` from the most
    recent row for Y. /action reads the latest row at decision time; /update
    walks the timeline to derive outcomes and rewards.
    """

    __tablename__ = "data_uploads"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), nullable=False)
    data = db.Column(db.JSON, nullable=False)
    request_timestamp = db.Column(db.DateTime, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        group_id: str,
        data: dict,
        request_timestamp: datetime.datetime,
        created_at: datetime.datetime | None = None,
    ):
        if created_at is None:
            created_at = datetime.datetime.now()
        self.group_id = group_id
        self.data = data
        self.request_timestamp = request_timestamp
        self.created_at = created_at

    def __repr__(self):
        return (
            f"<DataUpload group_id={self.group_id} "
            f"request_timestamp={self.request_timestamp}>"
        )


class Action(db.Model):
    """
    Database table to store action generated by the RL algorithm.
    """

    __tablename__ = "actions"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), nullable=False)
    rid = db.Column(db.String(255), unique=True, nullable=False)
    state = db.Column(db.JSON, nullable=True)
    decision_idx = db.Column(db.Integer, nullable=False)
    decision_type = db.Column(db.String(255), nullable=False)
    raw_context = db.Column(db.JSON, nullable=False)
    action = db.Column(db.Integer, nullable=False)
    action_prob = db.Column(db.Float, nullable=False)
    is_warmup = db.Column(db.Boolean, nullable=False, default=False)
    warmup_reason = db.Column(db.String(32), nullable=True)
    random_state = db.Column(db.JSON, nullable=False)
    model_parameters_id = db.Column(
        db.Integer, db.ForeignKey("model_parameters.id"), nullable=False
    )
    request_timestamp = db.Column(db.DateTime, nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)

    __table_args__ = (
        db.UniqueConstraint(
            "group_id",
            "decision_type",
            "decision_idx",
            name="uq_action_group_type_idx",
        ),
    )

    def __init__(
        self,
        group_id: str,
        action: int,
        rid: str,
        state: dict,
        decision_idx: int,
        decision_type: str,
        raw_context: dict,
        action_prob: float,
        random_state: dict,
        model_parameters_id: int,
        request_timestamp: datetime.datetime,
        is_warmup: bool = False,
        warmup_reason: str | None = None,
        timestamp: datetime.datetime | None = None,
    ):
        """
        Initialize the Action object.
        """
        if timestamp is None:
            timestamp = datetime.datetime.now()
        self.group_id = group_id
        self.action = action
        self.rid = rid
        self.state = state
        self.decision_idx = decision_idx
        self.decision_type = decision_type
        self.raw_context = raw_context
        self.action_prob = action_prob
        self.is_warmup = bool(is_warmup)
        self.warmup_reason = warmup_reason
        self.random_state = random_state
        self.model_parameters_id = model_parameters_id
        self.request_timestamp = request_timestamp
        self.timestamp = timestamp

    def __repr__(self):
        """
        Return a string representation of the Action object.
        """
        return f"<Action rid={self.rid}, group_id={self.group_id}, action={self.action}, state={self.state}, action_prob={self.action_prob}>"


class ModelParameters(db.Model):
    """
    Unified table for all decision-making-algorithm parameters.

    Holds either:
      - A legacy / fixed-probability row (only ``probability_of_action`` set), or
      - An Empirical-Bayes snapshot — local fit, pooled hyperparameters, or
        posterior — one row per (``snapshot_type``, ``group_id`` (nullable for
        pooled), ``decision_type``, ``agent_decision_index``).

    Every column except ``id`` and ``timestamp`` is nullable so the same table
    can house both shapes; the writing algorithm decides which fields to set.
    """

    __tablename__ = "model_parameters"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    # Legacy / fixed-probability field.
    probability_of_action = db.Column(db.Float, nullable=True)

    # Empirical-Bayes snapshot fields (absorbed from the former
    # ``empirical_bayes_snapshots`` table).
    snapshot_type = db.Column(db.String(64), nullable=True)
    group_id = db.Column(db.String(255), nullable=True)
    decision_type = db.Column(db.String(255), nullable=True)
    agent_decision_index = db.Column(db.Integer, nullable=True)
    sample_size = db.Column(db.Integer, nullable=True, default=0)
    feature_dim = db.Column(db.Integer, nullable=True)
    theta = db.Column(db.JSON, nullable=True)
    covariance = db.Column(db.JSON, nullable=True)
    perturbation = db.Column(db.JSON, nullable=True)
    metadata_json = db.Column(db.JSON, nullable=True)

    timestamp = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        probability_of_action: float | None = None,
        snapshot_type: str | None = None,
        group_id: str | None = None,
        decision_type: str | None = None,
        agent_decision_index: int | None = None,
        sample_size: int = 0,
        feature_dim: int | None = None,
        theta: list | None = None,
        covariance: list | None = None,
        perturbation: list | None = None,
        metadata_json: dict | None = None,
        timestamp: datetime.datetime | None = None,
    ):
        if timestamp is None:
            timestamp = datetime.datetime.now()
        self.probability_of_action = probability_of_action
        self.snapshot_type = snapshot_type
        self.group_id = group_id
        self.decision_type = decision_type
        self.agent_decision_index = agent_decision_index
        self.sample_size = sample_size
        self.feature_dim = feature_dim
        self.theta = theta
        self.covariance = covariance
        self.perturbation = perturbation
        self.metadata_json = metadata_json if metadata_json is not None else {}
        self.timestamp = timestamp

    def __repr__(self):
        if self.snapshot_type is not None:
            return (
                f"<ModelParameters snapshot_type={self.snapshot_type} "
                f"decision_type={self.decision_type} group_id={self.group_id} "
                f"agent_decision_index={self.agent_decision_index}>"
            )
        return f"<ModelParameters probability_of_action={self.probability_of_action}>"


class ThompsonSamplingParams(db.Model):
    """
    Thompson Sampling parameters per (group_id, decision_type).
    Each dyad and decision type has its own independent TS bandit.
    """

    __tablename__ = "thompson_sampling_params"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), nullable=False)
    decision_type = db.Column(db.String(255), nullable=False)
    params = db.Column(db.JSON, nullable=False)  # {action_0: {...}, action_1: {...}}
    updated_at = db.Column(db.DateTime, nullable=False)

    __table_args__ = (db.UniqueConstraint("group_id", "decision_type", name="uq_group_decision"),)

    def __init__(
        self,
        group_id: str,
        decision_type: str,
        params: dict,
        updated_at: datetime.datetime = None,
    ):
        if updated_at is None:
            updated_at = datetime.datetime.now()
        self.group_id = group_id
        self.decision_type = decision_type
        self.params = params
        self.updated_at = updated_at


class ModelUpdateRequests(db.Model):
    """
    Database table to store model update requests.
    """

    __tablename__ = "model_update_requests"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    update_id = db.Column(db.String(255), nullable=False)
    status = db.Column(db.String(50), nullable=False)
    request_timestamp = db.Column(db.DateTime, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    completed_at = db.Column(db.DateTime, nullable=True)
    error_message = db.Column(db.String(1024), nullable=True)

    def __init__(
        self,
        update_id: str,
        request_timestamp: datetime.datetime,
        status: str = "processing",
        created_at: datetime.datetime | None = None,
    ):
        """
        Initialize the ModelUpdateRequests object.

        The new design has no callback: completion is observed by reading
        `status` / `completed_at` (API-Spec §3.4), not POSTed anywhere.
        """
        if created_at is None:
            created_at = datetime.datetime.now()
        self.update_id = update_id
        self.request_timestamp = request_timestamp
        self.status = status
        self.created_at = created_at

    def __repr__(self):
        """
        Return a string representation of the ModelUpdateRequests object.
        """
        return f"<ModelUpdateRequests update_id={self.update_id}, status={self.status}>"


class StudyData(db.Model):
    """
    Update-derived (action, outcome) pairs (API-Spec §6.4).

    One row per (action, derived outcome), written during /update: the action
    is located in `actions`, the outcome fields are read from later
    `data_uploads` rows on the timeline (§5.3), and the scalar reward is
    computed and stored. Idempotent across /update re-runs — an existing row
    is updated in place if its outcome window has since filled in.
    """

    __tablename__ = "study_data"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), nullable=False)
    decision_idx = db.Column(db.Integer, nullable=False)
    decision_type = db.Column(db.String(255), nullable=False)
    action = db.Column(db.Integer, nullable=False)
    action_prob = db.Column(db.Float, nullable=False)
    state = db.Column(db.JSON, nullable=False)
    raw_context = db.Column(db.JSON, nullable=False)
    outcome = db.Column(db.JSON, nullable=False)
    reward = db.Column(db.Float, nullable=True)
    request_timestamp = db.Column(db.DateTime, nullable=False)
    derived_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, nullable=False)

    __table_args__ = (
        db.UniqueConstraint(
            "group_id",
            "decision_type",
            "decision_idx",
            name="uq_study_group_type_idx",
        ),
    )

    def __init__(
        self,
        group_id: str,
        decision_idx: int,
        decision_type: str,
        action: int,
        action_prob: float,
        state: list,
        raw_context: dict,
        outcome: dict,
        reward: float,
        request_timestamp: datetime.datetime,
        derived_at: datetime.datetime | None = None,
        created_at: datetime.datetime | None = None,
    ):
        """
        Initialize the StudyData object.
        """
        if created_at is None:
            created_at = datetime.datetime.now()
        self.group_id = group_id
        self.decision_idx = decision_idx
        self.decision_type = decision_type
        self.action = action
        self.action_prob = action_prob
        self.state = state
        self.raw_context = raw_context
        self.outcome = outcome
        self.reward = reward
        self.request_timestamp = request_timestamp
        self.derived_at = derived_at
        self.created_at = created_at

    def __repr__(self):
        """
        Return a string representation of the StudyData object.
        """
        return f"<StudyData group_id={self.group_id}, raw_context={self.raw_context}, action={self.action}, reward={self.reward}>"


class StandardizationBaseline(db.Model):
    """
    Per-dyad week-1 baselines used to standardize continuous state variables
    before they enter the learner (main.tex §3, "Variable Standardization").

    One row per (group_id, decision_type, variable_name). Populated once per
    dyad/agent at the first weekly /update after the dyad has accumulated
    week-1 data, and never modified thereafter.
    """

    __tablename__ = "standardization_baselines"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    group_id = db.Column(db.String(255), nullable=False)
    decision_type = db.Column(db.String(255), nullable=False)
    variable_name = db.Column(db.String(255), nullable=False)
    mu = db.Column(db.Float, nullable=False)
    sigma = db.Column(db.Float, nullable=False)
    sample_size = db.Column(db.Integer, nullable=False, default=0)
    created_at = db.Column(db.DateTime, nullable=False)

    __table_args__ = (
        db.UniqueConstraint(
            "group_id",
            "decision_type",
            "variable_name",
            name="uq_baseline_group_dt_var",
        ),
    )

    def __init__(
        self,
        group_id: str,
        decision_type: str,
        variable_name: str,
        mu: float,
        sigma: float,
        sample_size: int = 0,
        created_at: datetime.datetime | None = None,
    ):
        if created_at is None:
            created_at = datetime.datetime.now()
        self.group_id = group_id
        self.decision_type = decision_type
        self.variable_name = variable_name
        self.mu = float(mu)
        self.sigma = float(sigma)
        self.sample_size = int(sample_size)
        self.created_at = created_at


class UpdateReproducibilitySnapshot(db.Model):
    """
    Points to an on-disk full copy of data_uploads, actions (decision states),
    and groups taken immediately before a model update completes. Under the
    update-derived design study_data is itself produced during /update, so the
    snapshot copies the upstream data_uploads instead (API-Spec §6.9).
    """

    __tablename__ = "update_reproducibility_snapshots"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    update_id = db.Column(db.String(255), nullable=False)
    model_parameters_id = db.Column(db.Integer, nullable=True)
    snapshot_dir = db.Column(db.String(2048), nullable=False)
    data_uploads_count = db.Column(db.Integer, nullable=False, default=0)
    actions_count = db.Column(db.Integer, nullable=False, default=0)
    groups_count = db.Column(db.Integer, nullable=False, default=0)
    total_bytes = db.Column(db.BigInteger, nullable=False, default=0)
    created_at = db.Column(db.DateTime, nullable=False)

    def __init__(
        self,
        update_id: str,
        snapshot_dir: str,
        model_parameters_id: int | None = None,
        data_uploads_count: int = 0,
        actions_count: int = 0,
        groups_count: int = 0,
        total_bytes: int = 0,
        created_at: datetime.datetime | None = None,
    ):
        if created_at is None:
            created_at = datetime.datetime.now()
        self.update_id = update_id
        self.model_parameters_id = model_parameters_id
        self.snapshot_dir = snapshot_dir
        self.data_uploads_count = data_uploads_count
        self.actions_count = actions_count
        self.groups_count = groups_count
        self.total_bytes = total_bytes
        self.created_at = created_at
